config/routes.rb
Rails.application.routes.draw do

  root 'contacts#index'

  
    resources :calls
  

    resources :contacts
 

  

end

app/models/call.rb
class Call < ActiveRecord::Base
	belongs_to :contact , foreign_key: "number"
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_many :calls
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
	
	def index
	@call = Call.new
	@calls = Call.all

	@contact = Contact.new
	@contacts = Contact.all
	end

	def create
	call = params['call']
	number = call['number']
	time = call['time']
	@call = Call.create(number: number, time: time)
	redirect_to "/calls/show"
	end

	def show
	@calls = Call.all	
	end

	def edit
	@contacts = Contact.all
  	@call = Call.find(params[:id])
  	end

 	def update
	call = params['call']
  	number = call['number']
  	time = call['time']
  	@call = Call.find(params[:id])
  	@call.update(number: number , time: time)
  	redirect_to "/calls/show"
 	end



  	def destroy
  	Call.find(params[:id]).destroy
    redirect_to "/calls/show"
  	end


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def index
  	@contact = Contact.new
  	@contacts = Contact.all
  	@title = "Home"
  end

  def create
  	contact = params['contact']
  	name = contact['name']
  	number = contact['number']
  	@contact = Contact.create(name: name, number: number)
  	flash[:success] = "Contact created"
  	redirect_to "/contacts/show"
  end

  def show
  	@contacts = Contact.all
  	@title = "Contacts"
  end

  def edit
  	@contact = Contact.find(params[:id])
  	@title = @contact.name
  end


  def update
  	contact = params['contact']
  	name = contact['name']
  	number = contact['number']
  	@contact = Contact.find(params[:id])
  	@contact.update(name: name, number: number)
  	redirect_to "/contacts/show"
  end

  def destroy
  	Contact.find(params[:id]).destroy
    redirect_to "/contacts/show"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/calls/edit.html.erb
<p>Edit a call reservation</p>



<%= form_for @call do |f| %>

<p><%= f.label :name %></p>	
<p><%= f.collection_select(:number, @contacts, :id, :name, :include_blank => "Please select") %></p>

<p><%= f.label :time %></p>
<p><%= f.text_field :time  %></p>

<p><%= f.submit %></p>

<% end %>



<p><a href="/calls/show">View reserved calls</a></p>

app/views/calls/index.html.erb
<p>Please select contact and enter a time you want to make that call below:</p>

<%= form_for @call do |f| %>

<p><%= f.label :contact %></p>	
<p><%= f.collection_select(:number, @contacts, :id, :name, :include_blank => "Please select") %></p>

<p><%= f.label :Time_24hr_format %></p>
<p><%= f.text_field :time %></p>

<p><%= f.submit %></p>

<% end %>

<p><a href="/calls/show">View Reserved Calls</a></p>

app/views/calls/show.html.erb
<p>This is your reserved calls list</p>

<table border="1px">
	<tr>
		<td>Time</td><td>Name</td><td>Number<td>Manage</td>
	</tr>
<% @calls.each do |call| %>
	<tr>
		<td><%= call.time %></td>
	
		<td><%= call.contact.name %></td>

		<td><%= call.contact.number %></td>
		
		<td><%= link_to "Edit", edit_call_path(call) %> | <%= link_to "Remove", call, method: :delete, data: { confirm: "Are you sure?" } %></td>
	</tr>
<% end %>


</table>

<p><a href="/calls">reserve a call</a></p>

app/views/contacts/edit.html.erb
<p>Edit a contact</p>



<%= form_for @contact do |f| %>

<p><%= f.label :name %></p>	
<p><%= f.text_field :name  %></p>

<p><%= f.label :number %></p>
<p><%= f.text_field :number  %></p>

<p><%= f.submit %></p>

<% end %>

app/views/contacts/index.html.erb
<p>Please Enter the name and number you want to save bellow</p>

<%= form_for @contact do |f| %>

<p><%= f.label :name %></p>	
<p><%= f.text_field :name %></p>

<p><%= f.label :number %></p>
<p><%= f.text_field :number %></p>

<p><%= f.submit %></p>

<% end %>

<p><a href="/contacts/show">View Phonebook</a></p>

app/views/contacts/show.html.erb
<p>This is your contacts list</p>

<table border="1px">
	<tr>
		<td>Name</td><td>Number</td><td>Manage</td>
	</tr>
<% @contacts.each do |contact| %>
	<tr>
		<td><%= contact.name %></td>
		<td><%= contact.number %></td>
		<td><%= link_to "Edit", edit_contact_path(contact) %> | <%= link_to "Remove", contact, method: :delete, data: { confirm: "Are you sure?" } %></td>
	</tr>
<% end %>
</table>

<p><a href="/">Add a contact</a> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tuckshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag	'all'	%>
  <%= stylesheet_link_tag	'ie'	%>

  <%= javascript_include_tag	'jquery-1.7.2.min'	%>
  <%= javascript_include_tag	'jquery.main'	%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<!--[if lt IE 9]><link rel="stylesheet" type="text/css" href="css/ie.css" /><![endif]-->
</head>
<body>
	<div id="wrapper">
		<div id="content">
			<div class="c1">
				<div class="controls">
					<nav class="links">
						<ul>
							
							<li><a href="/contacts/show" class="ico3">Phonebook </a></li>
							<li><a href="/calls/show" class="ico3">Call Reservations</a></li>
							<li><a href="#" class="ico3">Call Notes</a></li>

						</ul>
					</nav>
					<div class="profile-box">
						
						<a href="#" class="btn-on">On</a>
					</div>
				</div>
				<div class="tabs">
					<div id="tab-1" class="tab">
						<article>
							<div class="text-section">
								<%= yield %>
						</article>
					</div>
				</div>
			</div>
		</div>
		<aside id="sidebar">
			<strong class="logo"><a href="/contacts/show">lg</a></strong>
			<ul class="tabset buttons">
				
				<li class="active">
					<a href="/contacts/show" class="ico3"><span>Phonebook</span><em></em></a>
					<span class="tooltip"><span>Phonebook</span></span>
				</li>
				<li>
					<a href="/calls/show" class="ico3"><span>Call Reservations</span><em></em></a>
					<span class="tooltip"><span>Call Reservations</span></span>
				</li>
				<li>
					<a href="#" class="ico3"><span>Call Notes</span><em></em></a>
					<span class="tooltip"><span>Call Notes</span></span>
				</li>
				
			</ul>
			<span class="shadow"></span>
		</aside>
	</div>
</body>
</html>

</body>
</html>